<?php
return array (
  0 => 
  array (
    'name' => '小懒猫资源',
    'rema' => '综合接口多种播放源',
    'flag' => 'xiaolanmaozy',
    'apis' => 'http://121.62.21.54:81/api.php/provide/vod/at/json/',
    'zylink' => 'http://121.62.21.54:81/',
    'coll' => '芒果视频,mgtv,1006,1|PPTV视频,pptv,1005,1|乐视视频,letv,1004,1|搜狐视频,sohu,1003,1|奇艺视频,qiyi,1002,1|优酷视频,youku,1001,1|腾讯视频,qq,1000,1|哔哩哔哩,bilibili,995,1',
    'type' => '2',
    'filter' => '0',
    'filter_from' => '',
    'opt' => '0',
    'sync_pic_opt' => '0',
    'tips' => '<span class="layui-badge layui-bg-green">我的收藏</span>',
    'collect_mid' => 1,
  ),
  1 => 
  array (
    'name' => '小懒猫资源',
    'rema' => '腾讯视频直链',
    'flag' => 'xiaolanmaozy',
    'apis' => 'http://121.62.21.54:81/api.php/provide/vod/from/qq/at/json/',
    'zylink' => 'http://121.62.21.54:81/',
    'coll' => '腾讯视频,qq,1000,1',
    'type' => '2',
    'filter' => '0',
    'filter_from' => '',
    'opt' => '0',
    'sync_pic_opt' => '0',
    'tips' => '<span class="layui-badge layui-bg-green">我的收藏</span>',
    'collect_mid' => 1,
  ),
  2 => 
  array (
    'name' => '789资源站',
    'rema' => '综合腾讯优酷爱奇艺等直连',
    'flag' => 'ziyuan789',
    'apis' => 'https://www.caiji.cyou/api.php/provide/vod/at/json/',
    'zylink' => 'https://www.789jiexi.com/789.php',
    'coll' => '芒果视频,mgtv,1006,1|PPTV视频,pptv,1005,1|乐视视频,letv,1004,1|搜狐视频,sohu,1003,1|奇艺视频,qiyi,1002,1|优酷视频,youku,1001,1|腾讯视频,qq,1000,1|哔哩哔哩,bilibili,995,1',
    'type' => '2',
    'filter' => '0',
    'filter_from' => '',
    'opt' => '0',
    'sync_pic_opt' => '0',
    'tips' => '<span class="layui-badge layui-bg-green">我的收藏</span>',
    'collect_mid' => 1,
  ),
  3 => 
  array (
    'name' => '极速资源站',
    'rema' => '国内CDN 不限速 秒播',
    'flag' => 'jisuzy',
    'apis' => 'https://jszyapi.com/api.php/provide/vod/from/jsyun/at/json/',
    'zylink' => 'http://www.jisuzy.com/',
    'coll' => '极速云播,jsyun,1043,1',
    'type' => '2',
    'filter' => '0',
    'filter_from' => '',
    'opt' => '0',
    'sync_pic_opt' => '0',
    'tips' => '<span class="layui-badge layui-bg-green">我的收藏</span>',
    'collect_mid' => 1,
  ),
  4 => 
  array (
    'name' => '非凡资源站',
    'rema' => 'HTTPS资源,无需播放器',
    'flag' => 'feifanzy',
    'apis' => 'http://cj.ffzyapi.com/api.php/provide/vod/from/feifan/at/json/',
    'zylink' => 'http://ffzy.tv/',
    'coll' => '非凡播放②,feifan,1002,1',
    'type' => '2',
    'filter' => '0',
    'filter_from' => '',
    'opt' => '0',
    'sync_pic_opt' => '0',
    'tips' => '<span class="layui-badge layui-bg-green">我的收藏</span>',
    'collect_mid' => 1,
  ),
);