<?php
return array (
  'bwm3u8' => 
  array (
    'status' => '1',
    'from' => 'bwm3u8',
    'show' => 'bwm3u8',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://bo.baiwanapi.com/?url=',
    'sort' => '99999',
    'tip' => '',
    'id' => 'bwm3u8',
  ),
  'dadim3u8' => 
  array (
    'status' => '1',
    'from' => 'dadim3u8',
    'show' => 'dadim3u8',
    'des' => 'dadim3u8 大地资源 www.dadizy.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '1001',
    'tip' => '',
    'id' => 'dadim3u8',
  ),
  'lzm3u8' => 
  array (
    'status' => '1',
    'from' => 'lzm3u8',
    'show' => '量子m3u8',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '1000',
    'tip' => '',
    'id' => 'lzm3u8',
  ),
  'wolong' => 
  array (
    'status' => '1',
    'from' => 'wolong',
    'show' => 'wolong',
    'des' => '卧龙资源',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.wolongzywcdn.com:65/m3u8.php?url=',
    'sort' => '1000',
    'tip' => '',
    'id' => 'wolong',
  ),
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '902',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
  '1080zyk' => 
  array (
    'status' => '1',
    'from' => '1080zyk',
    'show' => '1080zyk',
    'des' => 'http://1080zyku.com/',
    'ps' => '1',
    'parse' => 'https://vip.zykbf.com/?url=',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => '1080zyk',
  ),
  'zykyun' => 
  array (
    'status' => '1',
    'from' => 'zykyun',
    'show' => 'zykyun',
    'des' => 'http://1080zyku.com/',
    'ps' => '1',
    'parse' => '',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'zykyun',
  ),
  'wjm3u8' => 
  array (
    'status' => '1',
    'from' => 'wjm3u8',
    'show' => '无尽',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.wujinkk.com/dplayer/?url=',
    'sort' => '1',
    'tip' => '',
    'id' => 'wjm3u8',
  ),
);