<?php
return array (
  'bwm3u8' => 
  array (
    'status' => '1',
    'from' => 'bwm3u8',
    'show' => 'bwm3u8',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://bo.baiwanapi.com/?url=',
    'sort' => '99999',
    'tip' => '',
    'id' => 'bwm3u8',
  ),
  'liangzi' => 
  array (
    'status' => '1',
    'from' => 'liangzi',
    'show' => '量子资源2',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1230',
    'tip' => '无需安装任何插件',
    'id' => 'liangzi',
  ),
  'gsyun' => 
  array (
    'status' => '1',
    'from' => 'gsyun',
    'show' => '光速云资源①',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1215',
    'tip' => '无需安装任何插件',
    'id' => 'gsyun',
  ),
  'ukyun' => 
  array (
    'status' => '1',
    'from' => 'ukyun',
    'show' => 'U酷云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1210',
    'tip' => '无需安装任何插件',
    'id' => 'ukyun',
  ),
  'okm3u8' => 
  array (
    'status' => '1',
    'from' => 'okm3u8',
    'show' => 'OK资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1050',
    'tip' => '无需安装任何插件',
    'id' => 'okm3u8',
  ),
  'jsyun' => 
  array (
    'status' => '1',
    'from' => 'jsyun',
    'show' => '极速云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1043',
    'tip' => '无需安装任何插件',
    'id' => 'jsyun',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '芒果视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1006',
    'tip' => '无需安装任何插件',
    'id' => 'mgtv',
  ),
  'pptv' => 
  array (
    'status' => '1',
    'from' => 'pptv',
    'show' => 'PPTV视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1005',
    'tip' => '无需安装任何插件',
    'id' => 'pptv',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '乐视视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1004',
    'tip' => '无需安装任何插件',
    'id' => 'letv',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '搜狐视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1003',
    'tip' => '无需安装任何插件',
    'id' => 'sohu',
  ),
  'feifan' => 
  array (
    'status' => '1',
    'from' => 'feifan',
    'show' => '非凡播放②',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1002',
    'tip' => '无需安装任何插件',
    'id' => 'feifan',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '奇艺视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1002',
    'tip' => '无需安装任何插件',
    'id' => 'qiyi',
  ),
  'dadim3u8' => 
  array (
    'status' => '1',
    'from' => 'dadim3u8',
    'show' => 'dadim3u8',
    'des' => 'dadim3u8 大地资源 www.dadizy.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '1001',
    'tip' => '',
    'id' => 'dadim3u8',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '优酷视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1001',
    'tip' => '无需安装任何插件',
    'id' => 'youku',
  ),
  'kuaiyun' => 
  array (
    'status' => '1',
    'from' => 'kuaiyun',
    'show' => '快云资源1',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'kuaiyun',
  ),
  'kuaiyunbo' => 
  array (
    'status' => '1',
    'from' => 'kuaiyunbo',
    'show' => '快云资源2',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'kuaiyunbo',
  ),
  'lzm3u8' => 
  array (
    'status' => '1',
    'from' => 'lzm3u8',
    'show' => '量子m3u8',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '1000',
    'tip' => '',
    'id' => 'lzm3u8',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '腾讯视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'qq',
  ),
  'wolong' => 
  array (
    'status' => '1',
    'from' => 'wolong',
    'show' => 'wolong',
    'des' => '卧龙资源',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.wolongzywcdn.com:65/m3u8.php?url=',
    'sort' => '1000',
    'tip' => '',
    'id' => 'wolong',
  ),
  'bilibili' => 
  array (
    'status' => '1',
    'from' => 'bilibili',
    'show' => '哔哩哔哩',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '995',
    'tip' => '无需安装任何插件',
    'id' => 'bilibili',
  ),
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '902',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
  '1080zyk' => 
  array (
    'status' => '1',
    'from' => '1080zyk',
    'show' => '1080zyk',
    'des' => 'http://1080zyku.com/',
    'ps' => '1',
    'parse' => 'https://vip.zykbf.com/?url=',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => '1080zyk',
  ),
  'zykyun' => 
  array (
    'status' => '1',
    'from' => 'zykyun',
    'show' => 'zykyun',
    'des' => 'http://1080zyku.com/',
    'ps' => '1',
    'parse' => '',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'zykyun',
  ),
  'wjm3u8' => 
  array (
    'status' => '1',
    'from' => 'wjm3u8',
    'show' => '无尽',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.wujinkk.com/dplayer/?url=',
    'sort' => '1',
    'tip' => '',
    'id' => 'wjm3u8',
  ),
);