<?php
return array (
  'wjm3u8' => 
  array (
    'status' => '1',
    'from' => 'wjm3u8',
    'show' => '无尽资源',
    'des' => '无尽资源',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.wuvodbf.com/dplayer/?url=',
    'sort' => '10000',
    'tip' => '无需安装任何插件',
  ),
  '1080zy' => 
  array (
    'status' => '1',
    'from' => '1080zy',
    'show' => '1080资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1235',
    'tip' => '无需安装任何插件',
    'id' => '1080zy',
  ),
  '1080zyk' => 
  array (
    'status' => '1',
    'from' => '1080zyk',
    'show' => '优质资源1',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1231',
    'tip' => '无需安装任何插件',
    'id' => '1080zyk',
  ),
  'lzm3u8' => 
  array (
    'status' => '1',
    'from' => 'lzm3u8',
    'show' => '量子资源1',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1229',
    'tip' => '无需安装任何插件',
    'id' => 'lzm3u8',
  ),
  'wolong' => 
  array (
    'status' => '1',
    'from' => 'wolong',
    'show' => '卧龙资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1214',
    'tip' => '无需安装任何插件',
    'id' => 'wolong',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '芒果视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1006',
    'tip' => '无需安装任何插件',
    'id' => 'mgtv',
  ),
  'pptv' => 
  array (
    'status' => '1',
    'from' => 'pptv',
    'show' => 'PPTV视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1005',
    'tip' => '无需安装任何插件',
    'id' => 'pptv',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '乐视视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1004',
    'tip' => '无需安装任何插件',
    'id' => 'letv',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '搜狐视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1003',
    'tip' => '无需安装任何插件',
    'id' => 'sohu',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '奇艺视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1002',
    'tip' => '无需安装任何插件',
    'id' => 'qiyi',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '优酷视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1001',
    'tip' => '无需安装任何插件',
    'id' => 'youku',
  ),
  'heimuer' => 
  array (
    'status' => '1',
    'from' => 'heimuer',
    'show' => '黑木耳资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'heimuer',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '腾讯视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'qq',
  ),
  'bilibili' => 
  array (
    'status' => '1',
    'from' => 'bilibili',
    'show' => '哔哩哔哩',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '995',
    'tip' => '无需安装任何插件',
    'id' => 'bilibili',
  ),
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '902',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
);