export default {
    aliyun: {
        name: "阿里云盘",
        type: "aliyun",
        cron: "* * * * *",
        enabled: true,
        path: "/",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
    quark: {
        name: "夸克网盘",
        type: "quark",
        cron: "* * * * *",
        enabled: true,
        path: "/",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
    jianguoyun: {
        name: "坚果云盘",
        type: "jianguoyun",
        cron: "* * * * *",
        enabled: true,
        path: "/",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
    wolong: {
        name: "卧龙资源",
        type: "wolong",
        cron: "* * * * *",
        enabled: true,
        path: "https://collect.wolongzy.cc/api.php/provide/vod/?ac=list",
        playUrl: "https://jx.wolongzywcdn.com:65/m3u8.php?url=",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
    baiwan: {
        name: "百万资源",
        type: "baiwan",
        cron: "* * * * *",
        enabled: true,
        path: "https://api.bwzyz.com/api.php/provide/vod/at/json/",
        playUrl: "https://bf.bwzyapi.com/?url=",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
    liangzi: {
        name: "量子资源",
        type: "liangzi",
        cron: "* * * * *",
        enabled: true,
        path: "https://cj.lziapi.com/api.php/provide/vod/?ac=list",
        playUrl: "https://lziplayer.com/?url=",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
};
