export default {
    aliyun: {
        name: "阿里云盘",
        type: "aliyun",
        cron: "* * * * *",
        enabled: true,
        path: "/",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
    quark: {
        name: "夸克网盘",
        type: "quark",
        cron: "* * * * *",
        enabled: true,
        path: "/",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
    jianguoyun: {
        name: "坚果云盘",
        type: "jianguoyun",
        cron: "* * * * *",
        enabled: true,
        path: "/",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
    wolong: {
        name: "卧龙资源",
        type: "wolong",
        cron: "* * * * *",
        enabled: true,
        path: "https://collect.wolongzy.cc/api.php/provide/vod/?ac=detail",
        playUrl: "https://jx.wolongzywcdn.com:65/m3u8.php?url=",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
    wjm3u8: {
        name: "无尽资源",
        type: "wjm3u8",
        cron: "* * * * *",
        enabled: true,
        path: "https://api.wujinapi.me/api.php/provide/vod/?ac=detail",
        playUrl: "https://jx.wuvodbf.com/dplayer/?url=",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
    shandian: {
        name: "闪电资源",
        type: "shandian",
        cron: "* * * * *",
        enabled: true,
        path: "https://xsd.sdzyapi.com/api.php/provide/vod/?ac=detail",
        playUrl: "https://www.shankubf.com/m3u8/?url=",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
    liangzi: {
        name: "量子资源",
        type: "liangzi",
        cron: "* * * * *",
        enabled: true,
        path: "https://cj.lziapi.com/api.php/provide/vod/?ac=detail",
        playUrl: "https://lziplayer.com/?url=",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
    jingying: {
        name: "金鹰资源",
        type: "jingying",
        cron: "* * * * *",
        enabled: true,
        path: "https://jyzyapi.com/provide/vod/from/jinyingyun/at/json",
        playUrl: "https://hd.iapijy.com/play?url=",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
    youzhi: {
        name: "优质资源",
        type: "youzhi",
        cron: "* * * * *",
        enabled: true,
        path: "https://api.yzzy-api.com/inc/apijson.php?ac=detail",
        playUrl: "https://vip.zykbf.com/?url=",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
    yhm3u8: {
        name: "樱花资源",
        type: "yhm3u8",
        cron: "* * * * *",
        enabled: true,
        path: "https://m3u8.apiyhzy.com/api.php/provide/vod/?ac=detail",
        playUrl: "https://jx.yhzybf.com/player/jx.php?url=",
        categoryId: "",
        category: "动漫",
        tags: ["修仙"],
    },
};
